-- DONGARGAON RAILWAY GRAM PANCHAYAT DATABASE SCHEMA

-- 1. USERS TABLE
CREATE TABLE users (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  role TEXT DEFAULT 'citizen' CHECK (role IN ('citizen', 'admin', 'staff')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. COMPLAINTS TABLE
CREATE TABLE complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  author_name TEXT,
  author_email TEXT,
  is_anonymous BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'In Progress', 'Resolved')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SERVICE REQUESTS TABLE
CREATE TABLE service_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  service_type TEXT NOT NULL,
  details JSONB,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Processing', 'Approved', 'Rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. NOTICES TABLE
CREATE TABLE notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  date TEXT NOT NULL,
  category TEXT DEFAULT 'General',
  document_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. SCHEMES TABLE
CREATE TABLE schemes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheme_name TEXT NOT NULL,
  description TEXT,
  eligibility TEXT,
  documents_required TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. PANCHAYAT MEMBERS TABLE
CREATE TABLE panchayat_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  contact TEXT,
  email TEXT,
  image_url TEXT,
  order_index INT DEFAULT 0
);

-- RLS POLICIES

-- Enable RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE schemes ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Public can view notices" ON notices FOR SELECT USING (true);
CREATE POLICY "Public can view schemes" ON schemes FOR SELECT USING (true);
CREATE POLICY "Public can view members" ON panchayat_members FOR SELECT USING (true);

-- Complaint policies
CREATE POLICY "Anyone can submit complaints" ON complaints FOR INSERT WITH CHECK (true);
CREATE POLICY "Complaints are viewable by admins" ON complaints FOR SELECT USING (
  EXISTS (SELECT 1 FROM users WHERE users.id = auth.uid() AND users.role = 'admin')
);

-- Service Request policies
CREATE POLICY "Users can view their own requests" ON service_requests FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own requests" ON service_requests FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Admin write access (simplified example)
CREATE POLICY "Admins have full access" ON notices FOR ALL USING (
  EXISTS (SELECT 1 FROM users WHERE users.id = auth.uid() AND users.role = 'admin')
);
